name: Check Sync with Main

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  check-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Fetch main branch
      run: git fetch origin main

    - name: Check if branch is up-to-date with main
      id: check_sync
      run: |
        git merge-base --is-ancestor origin/main HEAD
      continue-on-error: true

    - name: Fail if not up-to-date
      if: steps.check_sync.outcome == 'failure'
      run: |
        echo "The branch is not up-to-date with main. Please rebase or merge main into your branch."
        exit 1
